source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.4.2'

gem 'rails', '~> 5.2.3'
gem 'sqlite3'
gem 'administrate'
gem 'administrate-field-enumerate'
gem 'administrate_exportable', path: File.path('../../')

group :development, :test do
  gem 'rb-readline'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.8'
  gem 'pry-byebug'
end
